// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public final class Entities {
  private Entities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_MyUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_MyUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_MyBlog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_MyBlog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_MyComment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_MyComment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_MyPermission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_MyPermission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_models_MyRole_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_models_MyRole_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016entities.proto\022\006models\"\217\001\n\006MyUser\022\n\n\002i" +
      "d\030\001 \001(\005\022\r\n\005email\030\002 \001(\t\022\020\n\010password\030\003 \001(\t" +
      "\022\020\n\010username\030\004 \001(\t\022\034\n\004role\030\005 \003(\0132\016.model" +
      "s.MyRole\022(\n\npermission\030\006 \003(\0132\024.models.My" +
      "Permission\"\237\001\n\006MyBlog\022\n\n\002id\030\001 \001(\005\022\r\n\005tit" +
      "le\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\021\n\ttimestamp\030\004" +
      " \001(\t\022\021\n\timagePath\030\005 \003(\t\022\036\n\006author\030\006 \001(\0132" +
      "\016.models.MyUser\022#\n\010comments\030\007 \003(\0132\021.mode" +
      "ls.MyComment\"Y\n\tMyComment\022\n\n\002id\030\001 \001(\005\022\017\n" +
      "\007comment\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t\022\034\n\004blo" +
      "g\030\004 \001(\0132\016.models.MyBlog\")\n\014MyPermission\022" +
      "\n\n\002id\030\001 \001(\005\022\r\n\005value\030\002 \001(\t\"/\n\006MyRole\022\020\n\010" +
      "roleType\030\001 \001(\t\022\023\n\013description\030\002 \001(\tB\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_models_MyUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_models_MyUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_MyUser_descriptor,
        new java.lang.String[] { "Id", "Email", "Password", "Username", "Role", "Permission", });
    internal_static_models_MyBlog_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_models_MyBlog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_MyBlog_descriptor,
        new java.lang.String[] { "Id", "Title", "Content", "Timestamp", "ImagePath", "Author", "Comments", });
    internal_static_models_MyComment_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_models_MyComment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_MyComment_descriptor,
        new java.lang.String[] { "Id", "Comment", "Timestamp", "Blog", });
    internal_static_models_MyPermission_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_models_MyPermission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_MyPermission_descriptor,
        new java.lang.String[] { "Id", "Value", });
    internal_static_models_MyRole_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_models_MyRole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_models_MyRole_descriptor,
        new java.lang.String[] { "RoleType", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
