// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface MyBlogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.treeleaf.MyBlog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string timestamp = 4;</code>
   * @return The timestamp.
   */
  String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>.com.treeleaf.MyUser author = 5;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>.com.treeleaf.MyUser author = 5;</code>
   * @return The author.
   */
  MyUser getAuthor();
  /**
   * <code>.com.treeleaf.MyUser author = 5;</code>
   */
  MyUserOrBuilder getAuthorOrBuilder();

  /**
   * <code>repeated .com.treeleaf.MyComment comments = 6;</code>
   */
  java.util.List<MyComment>
      getCommentsList();
  /**
   * <code>repeated .com.treeleaf.MyComment comments = 6;</code>
   */
  MyComment getComments(int index);
  /**
   * <code>repeated .com.treeleaf.MyComment comments = 6;</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .com.treeleaf.MyComment comments = 6;</code>
   */
  java.util.List<? extends MyCommentOrBuilder>
      getCommentsOrBuilderList();
  /**
   * <code>repeated .com.treeleaf.MyComment comments = 6;</code>
   */
  MyCommentOrBuilder getCommentsOrBuilder(
      int index);
}
