// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface MyBlogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:models.MyBlog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string timestamp = 4;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>repeated string imagePath = 5;</code>
   * @return A list containing the imagePath.
   */
  java.util.List<java.lang.String>
      getImagePathList();
  /**
   * <code>repeated string imagePath = 5;</code>
   * @return The count of imagePath.
   */
  int getImagePathCount();
  /**
   * <code>repeated string imagePath = 5;</code>
   * @param index The index of the element to return.
   * @return The imagePath at the given index.
   */
  java.lang.String getImagePath(int index);
  /**
   * <code>repeated string imagePath = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the imagePath at the given index.
   */
  com.google.protobuf.ByteString
      getImagePathBytes(int index);

  /**
   * <code>.models.MyUser author = 6;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>.models.MyUser author = 6;</code>
   * @return The author.
   */
  models.MyUser getAuthor();
  /**
   * <code>.models.MyUser author = 6;</code>
   */
  models.MyUserOrBuilder getAuthorOrBuilder();

  /**
   * <code>repeated .models.MyComment comments = 7;</code>
   */
  java.util.List<models.MyComment> 
      getCommentsList();
  /**
   * <code>repeated .models.MyComment comments = 7;</code>
   */
  models.MyComment getComments(int index);
  /**
   * <code>repeated .models.MyComment comments = 7;</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .models.MyComment comments = 7;</code>
   */
  java.util.List<? extends models.MyCommentOrBuilder> 
      getCommentsOrBuilderList();
  /**
   * <code>repeated .models.MyComment comments = 7;</code>
   */
  models.MyCommentOrBuilder getCommentsOrBuilder(
      int index);
}
