// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface MyRoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.treeleaf.MyRole)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roleType = 1;</code>
   * @return The roleType.
   */
  String getRoleType();
  /**
   * <code>string roleType = 1;</code>
   * @return The bytes for roleType.
   */
  com.google.protobuf.ByteString
      getRoleTypeBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
