// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface MyUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.treeleaf.MyUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  String getUsername();
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  java.util.List<MyRole>
      getRoleList();
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  MyRole getRole(int index);
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  int getRoleCount();
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  java.util.List<? extends MyRoleOrBuilder>
      getRoleOrBuilderList();
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  MyRoleOrBuilder getRoleOrBuilder(
      int index);

  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  java.util.List<MyPermission>
      getPermissionList();
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  MyPermission getPermission(int index);
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  int getPermissionCount();
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  java.util.List<? extends MyPermissionOrBuilder>
      getPermissionOrBuilderList();
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  MyPermissionOrBuilder getPermissionOrBuilder(
      int index);
}
