// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

import be.objectify.deadbolt.java.models.Subject;

import java.util.List;

/**
 * Protobuf type {@code com.treeleaf.MyUser}
 */
public final class MyUser extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.treeleaf.MyUser)
        MyUserOrBuilder, Subject {
private static final long serialVersionUID = 0L;
  // Use MyUser.newBuilder() to construct.
  private MyUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MyUser() {
    email_ = "";
    password_ = "";
    username_ = "";
    role_ = java.util.Collections.emptyList();
    permission_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MyUser();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MyUser(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              role_ = new java.util.ArrayList<MyRole>();
              mutable_bitField0_ |= 0x00000001;
            }
            role_.add(
                input.readMessage(MyRole.parser(), extensionRegistry));
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              permission_ = new java.util.ArrayList<MyPermission>();
              mutable_bitField0_ |= 0x00000002;
            }
            permission_.add(
                input.readMessage(MyPermission.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        role_ = java.util.Collections.unmodifiableList(role_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        permission_ = java.util.Collections.unmodifiableList(permission_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Entities.internal_static_com_treeleaf_MyUser_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Entities.internal_static_com_treeleaf_MyUser_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MyUser.class, MyUser.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private volatile Object email_;
  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  @Override
  public String getEmail() {
    Object ref = email_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  @Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    Object ref = email_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile Object password_;
  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  @Override
  public String getPassword() {
    Object ref = password_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    Object ref = password_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  private volatile Object username_;
  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  @Override
  public String getUsername() {
    Object ref = username_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  @Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    Object ref = username_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 5;
  private List<MyRole> role_;
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  @Override
  public List<MyRole> getRoleList() {
    return role_;
  }
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  @Override
  public List<? extends MyRoleOrBuilder>
      getRoleOrBuilderList() {
    return role_;
  }
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  @Override
  public int getRoleCount() {
    return role_.size();
  }
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  @Override
  public MyRole getRole(int index) {
    return role_.get(index);
  }
  /**
   * <code>repeated .com.treeleaf.MyRole role = 5;</code>
   */
  @Override
  public MyRoleOrBuilder getRoleOrBuilder(
      int index) {
    return role_.get(index);
  }

  public static final int PERMISSION_FIELD_NUMBER = 6;
  private List<MyPermission> permission_;
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  @Override
  public List<MyPermission> getPermissionList() {
    return permission_;
  }
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  @Override
  public List<? extends MyPermissionOrBuilder>
      getPermissionOrBuilderList() {
    return permission_;
  }
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  @Override
  public int getPermissionCount() {
    return permission_.size();
  }
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  @Override
  public MyPermission getPermission(int index) {
    return permission_.get(index);
  }
  /**
   * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
   */
  @Override
  public MyPermissionOrBuilder getPermissionOrBuilder(
      int index) {
    return permission_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, username_);
    }
    for (int i = 0; i < role_.size(); i++) {
      output.writeMessage(5, role_.get(i));
    }
    for (int i = 0; i < permission_.size(); i++) {
      output.writeMessage(6, permission_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, username_);
    }
    for (int i = 0; i < role_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, role_.get(i));
    }
    for (int i = 0; i < permission_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, permission_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MyUser)) {
      return super.equals(obj);
    }
    MyUser other = (MyUser) obj;

    if (getId()
        != other.getId()) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getRoleList()
        .equals(other.getRoleList())) return false;
    if (!getPermissionList()
        .equals(other.getPermissionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    if (getRoleCount() > 0) {
      hash = (37 * hash) + ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getRoleList().hashCode();
    }
    if (getPermissionCount() > 0) {
      hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
      hash = (53 * hash) + getPermissionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MyUser parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MyUser parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MyUser parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MyUser parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MyUser parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MyUser parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MyUser parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MyUser parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MyUser parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MyUser parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MyUser parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MyUser parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MyUser prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @Override
  public List<MyRole> getRoles() {
    return getRoleList();
  }

  @Override
  public List<MyPermission> getPermissions() {
    return getPermissionList();
  }

  @Override
  public String getIdentifier() {
    return getEmail();
  }

  /**
   * Protobuf type {@code com.treeleaf.MyUser}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.treeleaf.MyUser)
          MyUserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Entities.internal_static_com_treeleaf_MyUser_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Entities.internal_static_com_treeleaf_MyUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyUser.class, MyUser.Builder.class);
    }

    // Construct using com.treeleaf.MyUser.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRoleFieldBuilder();
        getPermissionFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      email_ = "";

      password_ = "";

      username_ = "";

      if (roleBuilder_ == null) {
        role_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        roleBuilder_.clear();
      }
      if (permissionBuilder_ == null) {
        permission_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        permissionBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Entities.internal_static_com_treeleaf_MyUser_descriptor;
    }

    @Override
    public MyUser getDefaultInstanceForType() {
      return MyUser.getDefaultInstance();
    }

    @Override
    public MyUser build() {
      MyUser result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MyUser buildPartial() {
      MyUser result = new MyUser(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.email_ = email_;
      result.password_ = password_;
      result.username_ = username_;
      if (roleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          role_ = java.util.Collections.unmodifiableList(role_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.role_ = role_;
      } else {
        result.role_ = roleBuilder_.build();
      }
      if (permissionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          permission_ = java.util.Collections.unmodifiableList(permission_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.permission_ = permission_;
      } else {
        result.permission_ = permissionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MyUser) {
        return mergeFrom((MyUser)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MyUser other) {
      if (other == MyUser.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (roleBuilder_ == null) {
        if (!other.role_.isEmpty()) {
          if (role_.isEmpty()) {
            role_ = other.role_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoleIsMutable();
            role_.addAll(other.role_);
          }
          onChanged();
        }
      } else {
        if (!other.role_.isEmpty()) {
          if (roleBuilder_.isEmpty()) {
            roleBuilder_.dispose();
            roleBuilder_ = null;
            role_ = other.role_;
            bitField0_ = (bitField0_ & ~0x00000001);
            roleBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRoleFieldBuilder() : null;
          } else {
            roleBuilder_.addAllMessages(other.role_);
          }
        }
      }
      if (permissionBuilder_ == null) {
        if (!other.permission_.isEmpty()) {
          if (permission_.isEmpty()) {
            permission_ = other.permission_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePermissionIsMutable();
            permission_.addAll(other.permission_);
          }
          onChanged();
        }
      } else {
        if (!other.permission_.isEmpty()) {
          if (permissionBuilder_.isEmpty()) {
            permissionBuilder_.dispose();
            permissionBuilder_ = null;
            permission_ = other.permission_;
            bitField0_ = (bitField0_ & ~0x00000002);
            permissionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPermissionFieldBuilder() : null;
          } else {
            permissionBuilder_.addAllMessages(other.permission_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MyUser parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MyUser) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private Object email_ = "";
    /**
     * <code>string email = 2;</code>
     * @return The email.
     */
    public String getEmail() {
      Object ref = email_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 2;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    public String getPassword() {
      Object ref = password_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private Object username_ = "";
    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    public String getUsername() {
      Object ref = username_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 4;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private List<MyRole> role_ =
      java.util.Collections.emptyList();
    private void ensureRoleIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        role_ = new java.util.ArrayList<MyRole>(role_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            MyRole, MyRole.Builder, MyRoleOrBuilder> roleBuilder_;

    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public List<MyRole> getRoleList() {
      if (roleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(role_);
      } else {
        return roleBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public int getRoleCount() {
      if (roleBuilder_ == null) {
        return role_.size();
      } else {
        return roleBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public MyRole getRole(int index) {
      if (roleBuilder_ == null) {
        return role_.get(index);
      } else {
        return roleBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder setRole(
        int index, MyRole value) {
      if (roleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoleIsMutable();
        role_.set(index, value);
        onChanged();
      } else {
        roleBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder setRole(
        int index, MyRole.Builder builderForValue) {
      if (roleBuilder_ == null) {
        ensureRoleIsMutable();
        role_.set(index, builderForValue.build());
        onChanged();
      } else {
        roleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder addRole(MyRole value) {
      if (roleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoleIsMutable();
        role_.add(value);
        onChanged();
      } else {
        roleBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder addRole(
        int index, MyRole value) {
      if (roleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoleIsMutable();
        role_.add(index, value);
        onChanged();
      } else {
        roleBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder addRole(
        MyRole.Builder builderForValue) {
      if (roleBuilder_ == null) {
        ensureRoleIsMutable();
        role_.add(builderForValue.build());
        onChanged();
      } else {
        roleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder addRole(
        int index, MyRole.Builder builderForValue) {
      if (roleBuilder_ == null) {
        ensureRoleIsMutable();
        role_.add(index, builderForValue.build());
        onChanged();
      } else {
        roleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder addAllRole(
        Iterable<? extends MyRole> values) {
      if (roleBuilder_ == null) {
        ensureRoleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, role_);
        onChanged();
      } else {
        roleBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder clearRole() {
      if (roleBuilder_ == null) {
        role_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        roleBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public Builder removeRole(int index) {
      if (roleBuilder_ == null) {
        ensureRoleIsMutable();
        role_.remove(index);
        onChanged();
      } else {
        roleBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public MyRole.Builder getRoleBuilder(
        int index) {
      return getRoleFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public MyRoleOrBuilder getRoleOrBuilder(
        int index) {
      if (roleBuilder_ == null) {
        return role_.get(index);  } else {
        return roleBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public List<? extends MyRoleOrBuilder>
         getRoleOrBuilderList() {
      if (roleBuilder_ != null) {
        return roleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(role_);
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public MyRole.Builder addRoleBuilder() {
      return getRoleFieldBuilder().addBuilder(
          MyRole.getDefaultInstance());
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public MyRole.Builder addRoleBuilder(
        int index) {
      return getRoleFieldBuilder().addBuilder(
          index, MyRole.getDefaultInstance());
    }
    /**
     * <code>repeated .com.treeleaf.MyRole role = 5;</code>
     */
    public List<MyRole.Builder>
         getRoleBuilderList() {
      return getRoleFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            MyRole, MyRole.Builder, MyRoleOrBuilder>
        getRoleFieldBuilder() {
      if (roleBuilder_ == null) {
        roleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                MyRole, MyRole.Builder, MyRoleOrBuilder>(
                role_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        role_ = null;
      }
      return roleBuilder_;
    }

    private List<MyPermission> permission_ =
      java.util.Collections.emptyList();
    private void ensurePermissionIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        permission_ = new java.util.ArrayList<MyPermission>(permission_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            MyPermission, MyPermission.Builder, MyPermissionOrBuilder> permissionBuilder_;

    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public List<MyPermission> getPermissionList() {
      if (permissionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(permission_);
      } else {
        return permissionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public int getPermissionCount() {
      if (permissionBuilder_ == null) {
        return permission_.size();
      } else {
        return permissionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public MyPermission getPermission(int index) {
      if (permissionBuilder_ == null) {
        return permission_.get(index);
      } else {
        return permissionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder setPermission(
        int index, MyPermission value) {
      if (permissionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionIsMutable();
        permission_.set(index, value);
        onChanged();
      } else {
        permissionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder setPermission(
        int index, MyPermission.Builder builderForValue) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.set(index, builderForValue.build());
        onChanged();
      } else {
        permissionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder addPermission(MyPermission value) {
      if (permissionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionIsMutable();
        permission_.add(value);
        onChanged();
      } else {
        permissionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder addPermission(
        int index, MyPermission value) {
      if (permissionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePermissionIsMutable();
        permission_.add(index, value);
        onChanged();
      } else {
        permissionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder addPermission(
        MyPermission.Builder builderForValue) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.add(builderForValue.build());
        onChanged();
      } else {
        permissionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder addPermission(
        int index, MyPermission.Builder builderForValue) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.add(index, builderForValue.build());
        onChanged();
      } else {
        permissionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder addAllPermission(
        Iterable<? extends MyPermission> values) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permission_);
        onChanged();
      } else {
        permissionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder clearPermission() {
      if (permissionBuilder_ == null) {
        permission_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        permissionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public Builder removePermission(int index) {
      if (permissionBuilder_ == null) {
        ensurePermissionIsMutable();
        permission_.remove(index);
        onChanged();
      } else {
        permissionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public MyPermission.Builder getPermissionBuilder(
        int index) {
      return getPermissionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public MyPermissionOrBuilder getPermissionOrBuilder(
        int index) {
      if (permissionBuilder_ == null) {
        return permission_.get(index);  } else {
        return permissionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public List<? extends MyPermissionOrBuilder>
         getPermissionOrBuilderList() {
      if (permissionBuilder_ != null) {
        return permissionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(permission_);
      }
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public MyPermission.Builder addPermissionBuilder() {
      return getPermissionFieldBuilder().addBuilder(
          MyPermission.getDefaultInstance());
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public MyPermission.Builder addPermissionBuilder(
        int index) {
      return getPermissionFieldBuilder().addBuilder(
          index, MyPermission.getDefaultInstance());
    }
    /**
     * <code>repeated .com.treeleaf.MyPermission permission = 6;</code>
     */
    public List<MyPermission.Builder>
         getPermissionBuilderList() {
      return getPermissionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            MyPermission, MyPermission.Builder, MyPermissionOrBuilder>
        getPermissionFieldBuilder() {
      if (permissionBuilder_ == null) {
        permissionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                MyPermission, MyPermission.Builder, MyPermissionOrBuilder>(
                permission_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        permission_ = null;
      }
      return permissionBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.treeleaf.MyUser)
  }

  // @@protoc_insertion_point(class_scope:com.treeleaf.MyUser)
  private static final MyUser DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MyUser();
  }

  public static MyUser getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MyUser>
      PARSER = new com.google.protobuf.AbstractParser<MyUser>() {
    @Override
    public MyUser parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MyUser(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MyUser> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MyUser> getParserForType() {
    return PARSER;
  }

  @Override
  public MyUser getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

