// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface MyUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:models.MyUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string username = 4;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>repeated .models.MyRole role = 5;</code>
   */
  java.util.List<models.MyRole> 
      getRoleList();
  /**
   * <code>repeated .models.MyRole role = 5;</code>
   */
  models.MyRole getRole(int index);
  /**
   * <code>repeated .models.MyRole role = 5;</code>
   */
  int getRoleCount();
  /**
   * <code>repeated .models.MyRole role = 5;</code>
   */
  java.util.List<? extends models.MyRoleOrBuilder> 
      getRoleOrBuilderList();
  /**
   * <code>repeated .models.MyRole role = 5;</code>
   */
  models.MyRoleOrBuilder getRoleOrBuilder(
      int index);

  /**
   * <code>repeated .models.MyPermission permission = 6;</code>
   */
  java.util.List<models.MyPermission> 
      getPermissionList();
  /**
   * <code>repeated .models.MyPermission permission = 6;</code>
   */
  models.MyPermission getPermission(int index);
  /**
   * <code>repeated .models.MyPermission permission = 6;</code>
   */
  int getPermissionCount();
  /**
   * <code>repeated .models.MyPermission permission = 6;</code>
   */
  java.util.List<? extends models.MyPermissionOrBuilder> 
      getPermissionOrBuilderList();
  /**
   * <code>repeated .models.MyPermission permission = 6;</code>
   */
  models.MyPermissionOrBuilder getPermissionOrBuilder(
      int index);
}
