// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface RequestBlogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.treeleaf.RequestBlog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 authorId = 4;</code>
   * @return The authorId.
   */
  int getAuthorId();
}
