// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entities.proto

package models;

public interface RequestCommentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.treeleaf.RequestComment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string comment = 1;</code>
   * @return The comment.
   */
  String getComment();
  /**
   * <code>string comment = 1;</code>
   * @return The bytes for comment.
   */
  com.google.protobuf.ByteString
      getCommentBytes();

  /**
   * <code>string blogTitle = 2;</code>
   * @return The blogTitle.
   */
  String getBlogTitle();
  /**
   * <code>string blogTitle = 2;</code>
   * @return The bytes for blogTitle.
   */
  com.google.protobuf.ByteString
      getBlogTitleBytes();
}
